tick('hs0');actionData('og',(window.gbar && window.gbar.bv)?window.gbar.bv.m :0);function e(id){return document.getElementById(id)}function v(id){return e(id).value}function vs(id,val){e(id).value=val}function d0(id){e(id).style.display="none"}function d1(id){e(id).style.display=""}function u(v){return"undefined"==typeof v}
function GXhrGet(url,opt_callback){var req;window.XMLHttpRequest?req=new XMLHttpRequest:"undefined"!=typeof ActiveXObject&&(req=new ActiveXObject("Microsoft.XMLHTTP"));req.onreadystatechange=function(){4==req.readyState&&200==req.status&&(opt_callback&&opt_callback(req.responseText),req.onreadystatechange=function(){})};req.open("GET",url,!0);req.send("")}
function dac(e,c){var name=e.className?String(e.className):"";if(name){for(var cn=name.split(/\s+/),found=!1,i=0;i<cn.length;++i)if(cn[i]==c){found=!0;break}found||cn.push(c);e.className=cn.join(" ")}else e.className=c}function drc(e,c){var o=e.className?String(e.className):"";if(o&&-1!=o.indexOf(c)){for(var cn=o.split(/\s+/),i=0;i<cn.length;++i)cn[i]==c&&cn.splice(i--,1);e.className=cn.join(" ")}}function msbi(isOGHeader,gbar){return isOGHeader&&gbar&&gbar.qfgq?gbar.qfgq():e("q_d")};function ErrorLogger(opt_debug,opt_reloadMessageEnabled,opt_expIds){this.counter_=0;this.eventId_=null;this.debug_=opt_debug;this.expIds_=opt_expIds;this.ticks_=[];this.showReload_=!0;this.reloadMessageEnabled_=opt_reloadMessageEnabled;this.errorListener_=null;var previousErrorHandler=window.onerror,me=this;window.onerror=function(var_args){previousErrorHandler&&previousErrorHandler.apply(null,arguments);me.log_.apply(me,arguments);me.errorListener_&&me.errorListener_.apply(me,arguments)}}
ErrorLogger.prototype.createXhr_=function(){var r=null;try{"undefined"!=typeof ActiveXObject&&(r=new ActiveXObject("Microsoft.XMLHTTP"))}catch(error){r=null}!r&&window.XMLHttpRequest&&(r=new XMLHttpRequest);return r};ErrorLogger.prototype.setErrorListener=function(eventListener){this.errorListener_=eventListener};ErrorLogger.prototype.clearErrorListener=function(){this.errorListener_=null};ErrorLogger.prototype.setEventId=function(vpage){this.eventId_=vpage.ei};ErrorLogger.prototype.tick=function(flowType,tick){flowType?this.ticks_.push(flowType+"."+tick):this.ticks_.push(tick)};ErrorLogger.prototype.updatePageUrl=function(url){var node=e("errormessage");node&&(node.href=-1!=this.getWindowLocation_().href.indexOf("err=")?"/":url+"&err=1")};ErrorLogger.prototype.disableReloadMessage=function(){this.showReload_=!1};ErrorLogger.prototype.enableReloadMessage=function(){this.showReload_=!0};ErrorLogger.prototype.log_=function(msg,file,line){this.reloadMessageEnabled_&&this.showReload_&&this.showReloadMessage();if(this.debug_){var c=window.console;c&&c.log.apply(c,arguments)}else if(5>=this.counter_){++this.counter_;var urlLines=[];try{for(var stacktrace=[],counter=0,c=this.log_.caller;null!=c;c=c.caller){var matches=c.toString().match(/function (\w*)/);if(matches&&matches[1]&&(stacktrace.push(matches[1]),c.caller==c)){stacktrace.push("*");break}if(40<counter)break;++counter}var enc=
encodeURIComponent;this.eventId_&&urlLines.push("ei="+this.eventId_);this.expIds_&&0<this.expIds_.length&&urlLines.push("e="+this.expIds_.join(","));if(0<this.ticks_.length){var ticksStr=this.ticks_.join(";"),len=ticksStr.length;400<len&&(ticksStr=ticksStr.substr(len-400),ticksStr.indexOf(";")&&(ticksStr=ticksStr.substr(ticksStr.indexOf(";")+1)));urlLines.push("cad=ticks:"+ticksStr)}urlLines.push("jsest="+enc(stacktrace.join("/").substr(0,400)));msg.substr?(urlLines.push("jsem="+enc(msg.substr(0,400))),urlLines.push("jsef="+enc(file.substr(0,800))),urlLines.push("jsel="+enc(line))):urlLines.push("jsem=ERROR_EVENT_NO_MSG_FILE_LINE");document.cookie&&-1!=document.cookie.indexOf("vt")&&urlLines.push("vt=fts");document.cookie&&-1!=document.cookie.indexOf("mgoic")&&urlLines.push("vt=mge")}catch(e){urlLines.push("ERROR_PROCESSING_ERROR")}var url="/maps/gen_204/jse?"+urlLines.join("&"),r=this.createXhr_();r&&setTimeout(function(){r.open("GET",url,!0);r.send(null)},0)}};ErrorLogger.prototype.getWindowLocation_=function(){return window.location};ErrorLogger.prototype.showReloadMessage=function(){e("errormessagehtml")&&d1("errormessagehtml")};(function(){var debug_mode=false;var reload_message_enabled=false;var exp_ids=[];window.gErrorLogger = new ErrorLogger(debug_mode,reload_message_enabled,exp_ids);})();(function(){var js_version='446c';var load_ei='rJEPUfnJLY2PiAer_ICgAQ';window.reportSlowLoadingMessage = function(){GXhrGet('/maps/gen_204?imp=slm&jsv=' + js_version + '&ei=' + load_ei);tick('slm');};GXhrGet('/maps/gen_204?imp=asl&jsv=' + js_version + '&ei=' + load_ei);})();function switchForm(name) {return false;}function flipDForm() {var f = e("d_form");var tmp = v("d_d");f.saddr.value = v("d_daddr");f.daddr.value = tmp;return false;}

function B(c){var args = [];var func;
this.arg = function(pos,val){args[pos]= val;return this;};
this.func = function(f){func = f;return this;};
this.check = function(){if (!func)
return;for (var i = 0;i < c;++i)
if (u(args[i]))
return;func.apply(this,args);};}
var vpLoad = new B(5);var vpLoadHome = new B(2);var gApplication = null;var gMasterPrintHandler = null;(function(){window.gPanelDefaultUrls=['/maps?f\x3dq\x26source\x3ds_q\x26hl\x3den\x26geocode\x3d\x26aq\x3d0\x26oq\x3dflinders+st+melb\x26sll\x3d-32.010396,135.119128\x26sspn\x3d123.183141,178.59375\x26ie\x3dUTF8\x26hq\x3dFlinders+Street,+Melbourne,+Victoria\x26t\x3dm','/maps/ms?f\x3dq\x26source\x3ds_q\x26hl\x3den\x26geocode\x3d\x26q\x3dFlinders+Street,+Melbourne,+Victoria\x26aq\x3d0\x26oq\x3dflinders+st+melb\x26ie\x3dUTF8\x26hq\x3dFlinders+Street,+Melbourne,+Victoria\x26t\x3dm\x26oe\x3dUTF8\x26msa\x3d10','','/maps/mm?source\x3ds_q\x26hl\x3den\x26geocode\x3d\x26q\x3dFlinders+Street,+Melbourne,+Victoria\x26aq\x3d0\x26oq\x3dflinders+st+melb\x26sll\x3d-32.010396,135.119128\x26sspn\x3d123.183141,178.59375\x26ie\x3dUTF8\x26hq\x3dFlinders+Street,+Melbourne,+Victoria\x26t\x3dm','','','/maps?hl\x3den','','/maps/myplaces?hl\x3den'];})();(function(){window.gDeviceCapabilities=[,,1];})();function getWindowHeight(){if (window.self && self.innerHeight){return self.innerHeight;}
if (document.documentElement &&
document.documentElement.clientHeight){return document.documentElement.clientHeight;}
return 0;}
function getWindowWidth(){if (window.self && self.innerWidth){return self.innerWidth;}
if (document.documentElement &&
document.documentElement.clientWidth){return document.documentElement.clientWidth;}
return 0;}
function getIFrameDocument(iframe){if (iframe.contentWindow){return iframe.contentWindow.document;}else {return iframe.contentDocument;}
}
function loadUrl(url,opt_opts){getIFrameDocument(e("vp")).location = url;return false;}
function openInfoWindow(id){return true;}
function openLbaInfoWindow(id,label){return true;}
function calculateOffsetTop(element,opt_top){var top = opt_top || null;var offset = 0;for (var elem = element;elem && elem != opt_top;elem = elem.offsetParent){offset += elem.offsetTop;}
return offset;}
function resizeAppCalcHeight(){return getWindowHeight();}
(function(){var adjust_map_height=false;var cityblock_pano_ratio=1;var small_height=630;var small_width=1000;var is_ie6=false;window.setSizeMode = function(){var height = resizeAppCalcHeight();var width = getWindowWidth();var newSize = '';if (height < small_height || width < small_width){newSize = 'small';}
drc(document.body,'small');dac(document.body,newSize);};window.resizeApp = function(){if (!is_ie6){setSizeMode();}
var height = resizeAppCalcHeight();var panelElem = e("panel");var mapElem = e("map");if (!mapElem){return;}
var mapHeight = height - calculateOffsetTop(mapElem);var panelHeight = height - calculateOffsetTop(panelElem);panelHeight += 4;var sp = e("spsizer");var resizerHeight = height - calculateOffsetTop(sp);if (adjust_map_height){var mclip = e("mclip");mapHeight -= mclip.offsetHeight;}
mapElem.style.height = Math.max(0,mapHeight)+ "px";panelElem.style.height = Math.max(0,panelHeight)+ "px";resizerHeight -= e("rv_panel").offsetHeight;sp.style.height = Math.max(0,resizerHeight)+ "px";var inlineCityblockDiv = e("inline_pano_div");if (inlineCityblockDiv){var cityblockDivHeight = mapHeight * cityblock_pano_ratio;inlineCityblockDiv.style.height = Math.max(0,cityblockDivHeight)+
"px";}
};})();setTimeout(function(){if (gApplication){return;}
e("loadmessage")&& d0("loadmessage");e("slowmessage")&& d1("slowmessage");if (e('loadmessagehtml').style.visibility != 'hidden'){reportSlowLoadingMessage();}
},10000);function onSearch(form){if (gApplication){gApplication.prepareMainForm(form);}
return true;}
var gIsHomeVPage = true;function loadHomePage(){eval("try { var sbi =  e('q_d') || gbar.qfgq(); sbi.focus(); } " +
"catch (ex) {}");vpLoadHome.arg(1,"homestate").check();}
function loadVPageStarted(){gIsHomeVPage = false;}
function loadVPage(v,s){loadVPageStarted();vpLoad.arg(1,v).arg(2,s).arg(4,false).check();}
tick('hs1');function recordCityblockLightningFlashLoadTime(){tick('cbl');}
function recordCityblockHeavyFlashLoadTime(){tick('cbh');}
